version: '3'

services:
  app:
    build: .
    container_name: rust_dev
    ports:
      - 9095:8080
    volumes:
      - ./code:/code
    tty: true
    restart: always
    environment:
      TZ: Asia/Tokyo
