version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports: 
      - 9091:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    tty: true
    restart: always
    environment:
      TZ: Asia/Tokyo
